
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AF', 'Afganistán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AL', 'Albania');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'DE', 'Alemania');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AD', 'Andorra');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AO', 'Angola');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AI', 'Anguila');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AG', 'Antigua y Barbuda');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AN', 'Antillas Neerlandesas');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AQ', 'Antártcodea');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SA', 'Arabia Saudí');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'DZ', 'Argelia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AR', 'Argentina');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AM', 'Armenia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AW', 'Aruba');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AU', 'Australia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AT', 'Austria');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AZ', 'Azerbaiyán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BS', 'Bahamas');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BH', 'Bahréin');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BD', 'Bangladesh');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BB', 'Barbados');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BZ', 'Belice');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BJ', 'Benín');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BM', 'Bermudas');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BY', 'Bielorrusia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BO', 'Bolivia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BA', 'Bosnia-Herzegovina');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BW', 'Botsuana');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BR', 'Brasil');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BN', 'Brunéi');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BG', 'Bulgaria');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BF', 'Burkina Faso');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BI', 'Burundi');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BT', 'Bután');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BE', 'Bélgica');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CV', 'Cabo Verde');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KH', 'Camboya');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CM', 'Camerún');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CA', 'Canadá');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TD', 'Chad');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CL', 'Chile');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CN', 'China');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CY', 'Chipre');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'VA', 'Ciudad del Vaticano');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CO', 'Colombia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KM', 'Comoras');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CG', 'Congo');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KP', 'Corea del Norte');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KR', 'Corea del Sur');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CR', 'Costa Rica');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CI', 'Costa de Marfil');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'HR', 'Croacia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CU', 'Cuba');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'DK', 'Dinamarca');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'DM', 'Dominica');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'EC', 'Ecuador');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'EG', 'Egipto');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SV', 'El Salvador');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AE', 'Emiratos Árabes Uncodeos');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ER', 'Eritrea');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SK', 'Eslovaquia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SI', 'Eslovenia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ES', 'España');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'US', 'Estados Uncodeos');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'EE', 'Estonia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ET', 'Etiopía');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PH', 'Filipinas');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'FI', 'Finlandia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'FJ', 'Fiyi');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'FR', 'Francia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GA', 'Gabón');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GM', 'Gambia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GE', 'Georgia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GH', 'Ghana');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GI', 'Gibraltar');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GD', 'Granada');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GR', 'Grecia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GL', 'Groenlandia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GP', 'Guadalupe');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GU', 'Guam');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GT', 'Guatemala');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GF', 'Guayana Francesa');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GG', 'Guernsey');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GN', 'Guinea');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GQ', 'Guinea Ecuatorial');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GW', 'Guinea-Bissau');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GY', 'Guyana');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'HT', 'Haití');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'HN', 'Honduras');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'HK', 'Hong Kong');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'HU', 'Hungría');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'IN', 'India');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ID', 'Indonesia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'IQ', 'Iraq');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'IE', 'Irlanda');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'IR', 'Irán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BV', 'Isla Bouvet');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CX', 'Isla Christmas');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NU', 'Isla Niue');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NF', 'Isla Norfolk');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'IM', 'Isla de Man');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'IS', 'Islandia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KY', 'Islas Caimán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CC', 'Islas Cocos');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CK', 'Islas Cook');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'FO', 'Islas Feroe');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GS', 'Islas Georgia del Sur y Sandwich del Sur');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'HM', 'Islas Heard y McDonald');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'FK', 'Islas Malvinas');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MP', 'Islas Marianas del Norte');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MH', 'Islas Marshall');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SB', 'Islas Salomón');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TC', 'Islas Turcas y Caicos');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'VG', 'Islas Vírgenes Británicas');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'VI', 'Islas Vírgenes de los Estados Uncodeos');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'UM', 'Islas menores alejadas de los Estados Uncodeos');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AX', 'Islas Åland');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'IL', 'Israel');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'IT', 'Italia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'JM', 'Jamaica');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'JP', 'Japón');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'JE', 'Jersey');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'JO', 'Jordania');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KZ', 'Kazajistán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KE', 'Kenia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KG', 'Kirguistán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KI', 'Kiribati');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KW', 'Kuwait');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LA', 'Laos');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LS', 'Lesoto');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LV', 'Letonia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LR', 'Liberia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LY', 'Libia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LI', 'Liechtenstein');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LT', 'Lituania');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LU', 'Luxemburgo');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LB', 'Líbano');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MO', 'Macao');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MK', 'Macedonia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MG', 'Madagascar');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MY', 'Malasia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MW', 'Malaui');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MV', 'Maldivas');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ML', 'Mali');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MT', 'Malta');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MA', 'Marruecos');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MQ', 'Martinica');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MU', 'Mauricio');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MR', 'Mauritania');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'YT', 'Mayotte');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'FM', 'Micronesia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MD', 'Moldavia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MN', 'Mongolia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ME', 'Montenegro');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MS', 'Montserrat');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MZ', 'Mozambique');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MM', 'Myanmar');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MX', 'México');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MC', 'Mónaco');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NA', 'Namibia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NR', 'Nauru');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NP', 'Nepal');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NI', 'Nicaragua');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NG', 'Nigeria');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NO', 'Noruega');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NC', 'Nueva Caledonia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NZ', 'Nueva Zelanda');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NE', 'Níger');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'OM', 'Omán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PK', 'Pakistán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PW', 'Palau');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PS', 'Palestina');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PA', 'Panamá');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PG', 'Papúa Nueva Guinea');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PY', 'Paraguay');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'NL', 'Países Bajos');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PE', 'Perú');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PN', 'Pitcairn');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PF', 'Polinesia Francesa');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PL', 'Polonia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PT', 'Portugal');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PR', 'Puerto Rico');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'QA', 'Qatar');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ZZ', 'Región desconoccodea o no válcodea');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'GB', 'Reino Uncodeo');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CF', 'República Centroafricana');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CZ', 'República Checa');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CD', 'República Democrática del Congo');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'DO', 'República Dominicana');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'RE', 'Reunión');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'RW', 'Ruanda');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'RO', 'Rumanía');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'RU', 'Rusia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'WS', 'Samoa');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'AS', 'Samoa Americana');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'BL', 'San Bartolomé');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'KN', 'San Cristóbal y Nieves');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SM', 'San Marino');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'MF', 'San Martín');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'PM', 'San Pedro y Miquelón');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'VC', 'San Vicente y las Granadinas');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SH', 'Santa Elena');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LC', 'Santa Lucía');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ST', 'Santo Tomé y Príncipe');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SN', 'Senegal');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'RS', 'Serbia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CS', 'Serbia y Montenegro');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SC', 'Seychelles');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SL', 'Sierra Leona');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SG', 'Singapur');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SY', 'Siria');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SO', 'Somalia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'LK', 'Sri Lanka');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SZ', 'Suazilandia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ZA', 'Sudáfrica');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SD', 'Sudán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SE', 'Suecia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'CH', 'Suiza');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SR', 'Surinam');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'SJ', 'Svalbard y Jan Mayen');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'EH', 'Sáhara Occcodeental');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TH', 'Tailandia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TW', 'Taiwán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TZ', 'Tanzania');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TJ', 'Tayikistán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'IO', 'Territorio Británico del Océano Índico');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TF', 'Territorios Australes Franceses');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TL', 'Timor Oriental');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TG', 'Togo');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TK', 'Tokelau');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TO', 'Tonga');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TT', 'Trincodead y Tobago');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TM', 'Turkmenistán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TR', 'Turquía');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TV', 'Tuvalu');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'TN', 'Túnez');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'UA', 'Ucrania');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'UG', 'Uganda');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'UY', 'Uruguay');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'UZ', 'Uzbekistán');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'VU', 'Vanuatu');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'VE', 'Venezuela');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'VN', 'Vietnam');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'WF', 'Wallis y Futuna');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'YE', 'Yemen');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'DJ', 'Yibuti');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ZM', 'Zambia');
INSERT INTO `country` (`version`,`code`, `name`) VALUES (0,'ZW', 'Zimbabue');


