
-- Languages --
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'fr','Francés','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'en','Inglés','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'ar','Árabe','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'ja','Japonés','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'es','Español','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'de','Alemán','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'it','Italiano','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'id','Indonesio','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'pt','Portugués','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'ko','Coreano','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'tr','Turco','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'ru','Ruso','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'nl','Neerlandés','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'fil','Filipino','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'msa','Malayo','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'zh-tw','Chino tradicional','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'zh-cn','Chino simplificado','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'hi','Hindi','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'no','Noruego','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'sv','Sueco','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'fi','Finés','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'da','Danés','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'pl','Polaco','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'hu','Húngaro','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'fa','Persa','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'he','Hebreo','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'th','Tailandés','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'uk','Ucraniano','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'cs','Checo','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'ro','Rumano','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'en-gb','Inglés británico','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'vi','Vietnamita','production');
INSERT INTO languages (`version`,`code`,`name`,`status`) VALUES (0,'bn','Bengalí','production');